### ISSUE TITLE
USER STORY: Delete a review

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#11]
## Epic
EPIC: Edit and delete review

## User Story
As a **logged-in user** I want to **delete my own review** so that I can **remove it if necessary**.

## Acceptance Criteria
- [x] When logged in and clicking on of my own reviews there vill be a delete-button
- [x] When the delete-button is clicked the review will be deleted
- [x] The review will be deleted from the review list and the number of reviews for the album will be updated

## Tasks
- [x] Add new component MoreDropdown.js
- [x] Update reviewPage with logic for showing MoreDropdown if current user is the owner of the review
- [x] Add handleDelete

**Comment by andersganander** [comment]
Added new component MoreDropdown.js and MoreDropdown.module.css
Updated reviewPage with logic for showing MoreDropdown if current user is the owner of the review
Added handleDelete
