### ISSUE TITLE
USER STORY: Search for reviews and albums

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#12]
## Epic
EPIC: Search

## User Story
As a **user** I want to **search for albums and reviews** so that I can **find specific reviews or discover new albums**.

## Acceptance Criteria
- [x] On the albums page there is a search bar
- [x] When entering a search criteria (title) the list is altered
- [x] On the reviews page there is a search bar where i can search for title and owner

## Tasks
- [x] Add searchfields in AlbumTalk_API 
- [x] Update AlbumsPage
- [x] Update ReviewPage

**Comment by andersganander** [comment]
- Added search field 'title' in AlbumList i AlbumTalk_API
- Added search fields 'album__title' and 'owner__username' in ReviewList i AlbumTalk_API

**Comment by andersganander** [comment]
- Updated css with style for searchbar
- Updated AlbumsPage.js
    - Added search input field
    - Updated fetchAlbums
- Updated ReviewsPage.js
   - Added search input field
   - Updated fetchReviews
