### ISSUE TITLE
USER STORY: Write a comment

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#13]
## Epic
EPIC: Comments

## User Story
As a **logged-in user** I want to **comment on reviews** so that I can **discuss the review and the album with other users.**

## Acceptance Criteria
- [x] AC 1  The system should allow logged-in users to add comments to reviews by showing an add button or icon on the review card. The number of comments for that review will also be shown.
- [x] AC 2 The system should display comments immediately after they are posted.
- [x] AC 3 A user should be able to respond to comments by writing a comment
- [x] AC 4 A user should be able to write several comments for the same review

## Tasks
- [x] Add css
- [x] Add CommentCreaateForm.js
- [x] Add ReviewPage
- [x] Update app.js (route to review)
- [x] add comments_count

**Comment by andersganander** [comment]
- Added Comment component and form
- Updated ReviewPage and Review with comments functionality
- Added css for comment and CommentCreateEditForm
- Updated App.js

- Added comments count in Albumtalk_api
