### ISSUE TITLE
USER STORY: Edit a comment

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#15]
## Epic
EPIC: Comments

## User Story
As a **logged in user** I can **edit my comments** so that I can **fix or update my existing comments**

## Acceptance Criteria
- [x] AC 1 The system should allow logged-in users to edit their own comments.
- [x] AC 2 When a comment is edited and saved the changed comment should be shown.

## Tasks
- [x] Update Comment.js
- [x] Add CommentEditForm

**Comment by andersganander** [comment]
- Updated Comment.js with functionality for edit and delete
- Added CommentEditForm
