### ISSUE TITLE
USER STORY: Like a review

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#16]
## Epic
EPIC: Comment and like

## User Story
As a **logged-in user** I can **like others' reviews** so that I can **express my agreement** 

## Acceptance Criteria
- [ ] AC 1 A like icon ( e g a heart) should be shown next to each review
- [ ] AC 2 If i click the like icon it should be filled
- [ ] AC 3 if i click the like icon again it should be un-filled

## Tasks
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by andersganander** [comment]
Decided to remove this user story
