### ISSUE TITLE
USER STORY: List reviews

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#17]
## Epic
EPIC: View reviews

## User Story
As a **user** i can **see a list of reviews ordered with the most recent reviews first** so that **i am up to date**

## Acceptance Criteria
- [x] AC 1 On the start page there is a list of reviews with the most recent reviews at the top 
- [x] AC 2 If a new review is added it will be shown at the top of the list

## Tasks
- [x] Add album title in the review card
- [x] Add a ReviewsPage
- [ ]

**Comment by andersganander** [comment]
-Added album_title in seralizer for reviews
- Added album_title in Review.js
- Added ReviewsPage
- Added route for Reviews in app.js
