### ISSUE TITLE
USER STORY: Infinite scroll functionality

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#20]
## Epic
EPIC: Navigation

## User Story
As a **user** I can **keep scrolling through the albums and reviews, that are loaded for me automatically,** so that I **don't have to click on "next page" etc**

## Acceptance Criteria
- [x] Albums are loaded while scrolling in the album list
- [x] Reviews are loaded while scrolling in the reviews list

## Tasks
- [x] Install infinite-scroll-component
- [x] Add infinite scroll to AlbumsPage.js
- [x] Add utils.js
- [x] Add infinite scroll to ReviewsPage.js

**Comment by andersganander** [comment]
- Installed infinite-scroll-component
- Added utils/utils.js with fetchMoreData
- Added infinite scroll component in AlbumsPage
- Added infinite scroll component in ReviewsPage
