### ISSUE TITLE
USER STORY: Navigate easily between pages

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#21]
## Epic
EPIC: Navigation

## User Story
As a **user** I can **view a navbar from every page** so that I can **navigate easily between pages**

## Acceptance Criteria
- [x] AC 1 There's a navbar at the top of the start page
- [x] AC 2 When i click an option in the menu bar a new page is shown
- [x] AC 3 On smaller screens a hamburger icon is shown

## Tasks
- [x] Add navbar component
- [x] Update app.js
- [x] Add NavBar.module.css and styling

**Comment by andersganander** [comment]
Added navbar component
Added navbar.module.css with style rules
Added routing i app.js
