### ISSUE TITLE
USER STORY: View profile page

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#22]
## Epic
EPIC: Profile page

## User Story
As a **user** I can **view other users profiles** so that I can **see their reviews and favorite album and learn more about them**

## Acceptance Criteria
- [x] AC 1 A profile page is shown when an Avatar is clicked
- [x] AC 2 The profile page shows number of reviews and the reviews

## Tasks
- [x] Create Profile.js
- [x] Create profile data context
- [x] Add ProfilePage.js

**Comment by andersganander** [comment]
Created Profile.js
Created profile data context
Added ProfilePage.js

Also had to do some minor changes to the AlbumTalkAPI:
- Add filter owner__profile to ReviewList
- Add reviews_count to profile serializer
