### ISSUE TITLE
USER STORY: Follow and unfollow users

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#24]
## Epic
EPIC: Follow/unfollow

## User Story
As a **logged in user** I can **follow and unfollow other users** so that I can **see posts by specific users in my posts feed**

## Acceptance Criteria
- [x] AC 1 A logged-in user can see a "Follow" button on other users' profiles if they are not currently following them.
- [x] AC 2 A "Unfollow" button is displayed if the logged-in user is already following a user.
- [x] AC 3 The button updates in real-time to reflect the follow/unfollow action without a page refresh.
- [x] AC 4 Clicking the "Follow" button successfully adds the selected user to the logged-in user's list of followed users.
- [x] AC 5 Clicking the "Unfollow" button successfully removes the selected user from the logged-in user's list of followed users.

**Comment by andersganander** [comment]
Added `handleFollow` and `handleUnfollow` in `ProfileDataContext.js`
Added `PopularProfiles.js`
Added `PopularProfiles` to `AlbumsPage` 
Added follow buttons to Profile component and ProfilePage
Updated styling
Added `followHelper` and `unfollowHelper` to `utils.js`
Added style for follow buttons in TButton.module.css
