### ISSUE TITLE
USER STORY: List of most rated albums

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#25]
## Epic
EPIC: View reviews

## User Story
As a **user** i can **see a list of the albums with the most rating** so that i can **find new, interesting music**

## Acceptance Criteria
- [x] AC 1 On the (albums page and) reviews page there will be a list of most reviewed albums to the right
- [ ] AC 2 On mobile the list will be shorter and shown above the albums/reviews
- [ ] AC 3

## Tasks
- [x] add ordering_filter for albums in AlbumTalk_API
- [x] add MostReviewedAlbums component
- [x] update ReviewsPage 
- [ ] Task 3

**Comment by andersganander** [comment]
- Added ordering_filter for reviews_count in AlbumList in AlbumTalk_API

**Comment by andersganander** [comment]
- Added component MostRatedAlbums
- Updated ReviewsPage to show MostRatedAlbums

Left to implement:
- Layout for mobile
- Styling
- Links to albums
