### ISSUE TITLE
USER STORY: Edit profile

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#26]
## Epic
EPIC: Profile page

## User Story
As a **logged in user** I can **edit my profile** so that I can **change my profile picture and bio and choose my favorite david bowie album**

## Acceptance Criteria
- [x] When a user is logged in there will be an edit button (or something similar) on the profile page
- [x] When the edit button is clicked there will be a form shown with fields for image and bio
- [x] When the profile is saved it will be showed with the new values

## Tasks
- [x] update MoreDropDown component
- [x] update ProfilePage
- [x] add ProfileEditForm
- [x] update app.js with routing for `/edit`
- [x] #51

**Comment by andersganander** [comment]
- Updated MoreDropDown.js
- Added ProfileEditForm
- Updated ProfilePage.js
- Updated app.js

**Comment by andersganander** [comment]
The functionality for adding a favorite album is put on hold for now and might be resumed later depending om prioritizaations.
