### ISSUE TITLE
USER STORY: Album List

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#30]
## Epic
EPIC: Albums

## User Story
As a **user** i can **see a list of albums ordered by release date** so i can **easily find the album i want to review or discuss with others.**

## Acceptance Criteria
- [x] AC 1 A list of albums is shown on the startpage

## Tasks
- [x] Connect the front end with the backend api with axios 
- [x] Create a Album component
- [x] Create Album page
- [x] Create Albums page
- [x] Add basic styling

**Comment by andersganander** [comment]
Commited in order to have the latest code available for tutor. 
The aalbums page does not show any albums.

**Comment by andersganander** [comment]
Bug #39 fixed.
