### ISSUE TITLE
TODO Install libraries

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#37]
Just to not forget...
- [x] Add App.module.css in src
- [x] react-router-dom
- [x] import browserrouter in index.js
- [x] axios
