### ISSUE TITLE
Add links for easy navigation

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#49]
## Epic
EPIC: Navigation

## User Story
As a user i can navigate between some pages with direct links so that I don't need to use the navbar 

## Acceptance Criteria
- [x] In the review list the titles will be clickable links leading tothe reviewed album
- [ ] At the bottom of the Album page (after the reviews) there will be a link back to the previous page (which could be album list or review list)
- [ ] AC 3

## Tasks
- [x] Update Review.js
- [x] Update Album page

**Comment by andersganander** [comment]
- added link to album title in review list
- added button at the end of album page with `history.goBack()`
