### ISSUE TITLE
USER STORY: Visual rating

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#50]
## Epic
EPIC: Write review

## User Story
As a **user** I want to **use stars (or other symbols) to rate an album** so that **it's easier to rate**.

## Acceptance Criteria
- [x] When writing a review there will be "empty" stars to be used for rating
- [x] When a review is shown the rating will be shown with stars
- [x] The Edit form will also use stars

## Tasks
- [x] Install `react-simple-star-rating`
- [x] Update Review.js
- [x] Update ReviewCreateForm.js
- [x] Update ReviewEditForm.js

**Comment by andersganander** [comment]
- Installed react-simple-star-rating
- Added Rating component i Review.js
- Added Rating component and handleRating in ReviewCreateForm and ReviewEditForm
