### ISSUE TITLE
update ProfileEditForm with select field for favourite album

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#51]
When editing their profile the user will be able to select their favourite Bowie album.

- [x] Install react-select
- [x] update ProfileEditForm with select component
- [ ] fetch data from API to populate select
- [ ] Update ProfileEditForm with code to update Favourite
- [ ] Update API

**Comment by andersganander** [comment]
Closing this issue due to a changed idea on how to implement this functionality. Instead of choosing the favourite album in the edit profile form, the user will be able to choose their favourite album by clicking an icon on an album in the album list view.
