### ISSUE TITLE
USER STORY: Like favourite albums

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#58]
## Epic
EPIC: Albums

## User Story
As a **logged-in user** I can **add a favourite album** so that other users can **see what i like** 

## Acceptance Criteria
- [x] AC 1 A favourite icon ( e g a star) should be shown next to each album
- [x] AC 2 If i click the like icon it should be filled
- [x] AC 3 if i click the like icon again it should be un-filled
- [x] #62

## Tasks
- [x] Add `handleFavorite` in `Album.js`
- [x] Add `handleUnfavorite` in `Album.js`
- [x] Add styling rules for hovering over star and staroutline
- [x] Add code for calling `handleFavorite` and `handleUnfavorite` when clicking the star icon

**Comment by andersganander** [comment]
Added `handleFavorite` in `Album.js`
Add `handleUnfavorite` in `Album.js`
Add styling rules for hovering over star and staroutline
Add code for calling `handleFavorite` and `handleUnfavorite` when clicking the star icon
