### ISSUE TITLE
USER STORY: Log in

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#6]
## Epic
EPIC: Authentication

## User Story
As a **user**, I want to **be able to log in** so that **I can write and manage my album reviews.**

## Acceptance Criteria
- [x] AC 1 On the start page there will be a log in option
- [x] AC 2 The user will be able to logi using username and password
- [x] AC 3 The options in the menu bar will reflect the logged in state
- [x] AC 4 After logging in the user will remain logged in up until 24 hours

## Tasks
- [x] Add signinform component
- [x] Change image
- [x] Add user context
- [x] #40
- [x] #41

**Comment by andersganander** [comment]
Added signinform page
Added user context and used it to show logged in user in navbar

**Comment by andersganander** [comment]
All tasks and related issues implemented
