### ISSUE TITLE
USER STORY: Write a review

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#7]
## Epic
EPIC: Write review

## User Story
As a **logged-in user** I want to **write a review for an album** so that **I can share them with other users**.

## Acceptance Criteria
- [x] AC 1 When a user is logged in there will be a review-button on each album card showing the number of reviews for that specific album
- [ ] AC 2 When clicking the button there will be a form with prepopoulated fields for artist, album and editable field for review and rating. Beneath the form there will be other reviews for the same album.
- [x] AC 3 When the review is saved the number of review will be increased by one

## Tasks
- [x] Add reviews icon in album page
- [x] Create ReviewCreateEditForm css
- [x] Create ReviewCreateForm
- [x] Update AlbumPage.js
- [x] #45
- [x] #46

**Comment by andersganander** [comment]
Added basic functionality for write reviev. Filter for showing the correct reviews and count functionality will be handled in separate issues.

**Comment by andersganander** [comment]
For now the review form only contains fields for content and rating. The following changes will be added later on:
- Add album title (and maybe artist...)
- Replace the number field for rating with a react component (e g simple stars rating)
