### ISSUE TITLE
TODO IDAG

### ISSUE THREAD

**Issue by andersganander** [andersganander/albumtalk#79]
- [x] Uppdatera db-url 
- [x] Skriv klart readme för api
    - [x] Deploy till Heroku
    - [x] UptimeRobot
    - [x] Intro
- [ ] Gör testing.md
- [ ] Readme.md för web-app
- [ ] deploya api
- [ ] deploya FE
- [ ]

**Comment by andersganander** [comment]
Replaced by #43
